# Generated by Django 4.0.5 on 2023-01-12 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_venue_address_alter_venue_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=300, validators=[django.core.validators.BaseValidator.clean], verbose_name='Vanue address'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='email_address',
            field=models.EmailField(blank=True, max_length=120, validators=[django.core.validators.EmailValidator()], verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=120, validators=[django.core.validators.BaseValidator.clean], verbose_name='Vanue Name'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.validate_integer], verbose_name='Contact phone'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='venue',
            name='zip_code',
            field=models.CharField(max_length=30, validators=[django.core.validators.validate_integer], verbose_name='Vanue zip code'),
        ),
    ]
