# Generated by Django 4.0.5 on 2023-01-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
